version: 2.1

jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:v1.37-alpine

    working_directory: ~/my-project

    steps:
      - checkout
      - run: golangci-lint run

  build:
    docker:
      - image: circleci/golang:1.15.11
    
    working_directory: ~/my-project

    environment:
      TEST_RESULTS: /tmp/test-results
      GO111MODULE: "on"

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}        

      - run:
          name: Install Dependencies
          command: go mod download

      - run:
          name: Go Test
          command:
            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- $PACKAGE_NAMES

workflows:
  version: 2
  install-run:
    jobs:
      - build
      - lint
